//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labyrinth {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MenuMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Labyrinth.MenuMessages", typeof(MenuMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the scoreboard is empty..
        /// </summary>
        internal static string EmptyScoreboard {
            get {
                return ResourceManager.GetString("EmptyScoreboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to continue, you can enter &quot;r&quot; for restart the game or &quot;e&quot; for exit..
        /// </summary>
        internal static string EndOrNewGame {
            get {
                return ResourceManager.GetString("EndOrNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your move. For the direction left, right, up and down you can use the arrows..
        /// </summary>
        internal static string EnterMove {
            get {
                return ResourceManager.GetString("EnterMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your name for the top scoreboard:.
        /// </summary>
        internal static string EnterPlayerName {
            get {
                return ResourceManager.GetString("EnterPlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Good Bye!.
        /// </summary>
        internal static string Goodbye {
            get {
                return ResourceManager.GetString("Goodbye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Invalid command! 
        ///Use:	
        ///- &apos;t&apos; to view the top scoreboard,	
        ///- &apos;r&apos; to start a new game	
        ///- &apos;e&apos; to quit the game.	
        ///- the arrows for the directions.
        /// </summary>
        internal static string InvalidCommand {
            get {
                return ResourceManager.GetString("InvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. {1} --&gt; {2} moves
        ///.
        /// </summary>
        internal static string PlayerResult {
            get {
                return ResourceManager.GetString("PlayerResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Congratulations! You escaped in {0} moves..
        /// </summary>
        internal static string ShowMovesCount {
            get {
                return ResourceManager.GetString("ShowMovesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Welcome to “Labirinth” game! You should try to escape from it.
        ///The &apos;*&apos; is the player, the &apos;#&apos; are the walls of labyrinth. You should try to go through the &apos;-&apos; to some of the ends of the labyrinth.
        ///Use:
        ///- &apos;t&apos; to view the top scoreboard, 
        ///- &apos;r&apos; to start a new game
        ///- &apos;e&apos; to quit.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
